# 测试项目,根据所填写内容，会在报告中生成相关项目的报告
project_name: GM
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 罗宇琦
# 报告通知类型：0: 不发送通知 1：飞书通知
notification_type: 1
# 收集失败的用例开关，整理成excel报告的形式
excel_report: True
# 飞书通知
lark:
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/e8320b45-dc71-417e-b297-a69615bf3ac4

# pytest相关配置
pytest:
  - --reruns=1  # 失败重测次数
  - --reruns-delay=2 # 失败重测间隔
  - --count=1 # 循环次数
  - --random-order # 随机执行
  - D:\pyauto\repos\lxl\test_xxx.py  # 脚本选择 注释执行repos目录下所有用例
#  - D:\pyauto\repos\GM\TeenDriver\test_teen_driver.py::test_399718  # 脚本选择 注释执行repos目录下所有用例

# 测试对象性能监控 logcat, memory, cpu, fps, thread_num, 确保测试对象日期时间正确
perf:
  # 性能监控开关
  switch: True
  # 对象apk
  package: com.gm.hmi.settings
  frequency: 5





