# 测试项目,根据所填写内容，会在报告中生成相关项目的报告
project_name: lg
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 罗宇琦
# 报告通知类型：0: 不发送通知 1：飞书通知
notification_type: 0
# 收集失败的用例开关，整理成excel报告的形式
excel_report: True
# 飞书通知
lark:
#  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/6cc12558-21d9-4c51-87a3-8786657e4c16
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/e1d45e2f-acfd-4cf4-a521-94a30deb21b0




