# 测试项目,根据所填写内容，会在报告中生成相关项目的报告
project_name: GM
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 罗宇琦
# 报告通知类型：0: 不发送通知 1：飞书通知
notification_type: 0
# 收集失败的用例开关，整理成excel报告的形式
excel_report: True
# 飞书通知
lark:
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/e1d45e2f-acfd-4cf4-a521-94a30deb21b0
#  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/e8320b45-dc71-417e-b297-a69615bf3ac4

# 测试对象性能监控 logcat, memory, cpu, fps, thread_num, 确保测试对象日期时间正确
perf:
  # 性能监控开关
  switch: True
  # 对象apk
  package: com.gm.hmi.settings
  frequency: 5





